# Generated by Django 3.0.6 on 2020-05-12 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humi_land', models.CharField(default='', max_length=20, verbose_name='土壤湿度')),
                ('humi_area', models.CharField(default='', max_length=20, verbose_name='大气湿度')),
                ('temp_area', models.CharField(default='', max_length=20, verbose_name='空气温度')),
                ('temp_land', models.CharField(default='', max_length=20, verbose_name='土壤温度')),
                ('illu', models.CharField(default='', max_length=20, verbose_name='光照')),
                ('pres', models.CharField(default='', max_length=20, verbose_name='压强')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('incubator_iden', models.CharField(max_length=20, verbose_name='培养箱编号')),
            ],
            options={
                'verbose_name': '控制记录',
                'verbose_name_plural': '控制记录',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humi', models.CharField(default='', max_length=20, verbose_name='湿度')),
                ('temp', models.CharField(default='', max_length=20, verbose_name='温度')),
                ('pm', models.CharField(default='', max_length=20, verbose_name='粉尘')),
                ('jingdu', models.CharField(default='', max_length=20, verbose_name='经度')),
                ('weidu', models.CharField(default='', max_length=20, verbose_name='维度')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='采集数据时间')),
            ],
            options={
                'verbose_name': '数据信息',
                'verbose_name_plural': '数据信息',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='DataWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailtitle', models.CharField(default='浓度超标了', max_length=50, verbose_name='邮件标题')),
                ('messageContent', models.TextField(default='报警！', verbose_name='报警内容')),
                ('value', models.IntegerField(default=100, verbose_name='阈值')),
                ('interval', models.IntegerField(default=10, verbose_name='报警时间间隔')),
                ('level', models.CharField(choices=[('primary', '初级报警'), ('serious', '严重报警'), ('fatal', '致命报警')], default='primary', max_length=20, verbose_name='报警类型')),
            ],
            options={
                'verbose_name': '报警信息',
                'verbose_name_plural': '报警信息',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humi_land', models.CharField(default='', max_length=20, verbose_name='土壤湿度')),
                ('humi_area', models.CharField(default='', max_length=20, verbose_name='大气湿度')),
                ('temp_area', models.CharField(default='', max_length=20, verbose_name='空气温度')),
                ('temp_land', models.CharField(default='', max_length=20, verbose_name='土壤温度')),
                ('illu', models.CharField(default='', max_length=20, verbose_name='光照')),
                ('pres', models.CharField(default='', max_length=20, verbose_name='压强')),
                ('longi', models.CharField(default='', max_length=20, verbose_name='经度')),
                ('lati', models.CharField(default='', max_length=20, verbose_name='维度')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='采集数据时间')),
                ('image', models.TextField(blank=True, null=True, verbose_name='监控图片')),
                ('incubator_iden', models.CharField(max_length=20, verbose_name='培养箱编号')),
            ],
            options={
                'verbose_name': '培养箱环境数据',
                'verbose_name_plural': '培养箱环境数据',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('iden', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('key', models.CharField(default='zhiyaocubator', max_length=20, verbose_name='密钥')),
                ('stat', models.CharField(choices=[('disconnected', '未连接'), ('connected', '已连接'), ('breakdown', '故障')], default='disconnected', max_length=20)),
                ('user_phon', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '培养箱',
                'verbose_name_plural': '培养箱',
                'ordering': ('iden',),
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailtitle', models.CharField(default='浓度超标了', max_length=50, verbose_name='邮件标题')),
                ('messageContent', models.TextField(default='报警！', verbose_name='报警内容')),
                ('value', models.IntegerField(default=100, verbose_name='阈值')),
                ('interval', models.IntegerField(default=10, verbose_name='报警时间间隔')),
                ('level', models.CharField(choices=[('primary', '初级报警'), ('serious', '严重报警'), ('fatal', '致命报警')], default='primary', max_length=20, verbose_name='报警类型')),
            ],
            options={
                'verbose_name': '报警信息',
                'verbose_name_plural': '报警信息',
            },
        ),
        migrations.CreateModel(
            name='SaveWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentvalue', models.CharField(default='', max_length=10, verbose_name='报警平均值')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='报警时间')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotSystem.Warning', verbose_name='所属报警')),
            ],
            options={
                'verbose_name': '报警信息记录',
                'verbose_name_plural': '报警信息记录',
            },
        ),
        migrations.CreateModel(
            name='SaveDataWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentvalue', models.CharField(default='', max_length=10, verbose_name='报警平均值')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='报警时间')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotSystem.Warning', verbose_name='所属报警')),
            ],
            options={
                'verbose_name': '报警信息记录',
                'verbose_name_plural': '报警信息记录',
            },
        ),
    ]
