# Generated by Django 3.0.6 on 2020-05-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon', models.CharField(max_length=11, unique='True', verbose_name='电话号码')),
                ('stat', models.CharField(choices=[('alive', '活跃'), ('silence', '禁言'), ('restrict', '限制登录')], default='alive', max_length=20, verbose_name='账户状态')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('secret', '保密')], default='secret', max_length=20, verbose_name='性别')),
                ('img', models.TextField(default='md.img', verbose_name='头像')),
                ('intr', models.TextField(default='一个神秘的果壳', verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户验证信息')),
            ],
            options={
                'verbose_name': '用户配置文件',
                'verbose_name_plural': '用户配置文件',
            },
        ),
    ]
